baseURL = "https://juancgalan.com/"
languageCode = "en-us"
title = "Dr. Juan Carlos Galan Hernandez"

theme = "forty"

googleAnalytics = ""
disqusShortname = ""


[params]
    name = "Juan Carlos Galán Hernández"
    description = "Developer, Designer, Researcher"

    custom_css = []
    custom_js = []
    favicon = "favicon.ico"

    image = ""

    [params.error404]
        heading = "Page couldn't be found"
        text = "Please visit [this page](/)"

    [params.navigation]
        title = "Unlimited Src Works"
        subtitle = "by Juan Carlos Galán Hernández"
        menu = "Menu"

    [[params.navigation.links]]
        name = "Home"
        url = "#"

    [[params.navigation.links]]
        name = "Blog"
        url = "blog"

[params.banner]
    title = "Juan Carlos Galán Hernández"
    subtitle = "Developer, Designer, Reseacher"
    buttonText = "About me"
        